# Generated by Django 6.0.2 on 2026-03-02 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_places', to='schools.school')),
            ],
            options={
                'db_table': 'internship_places',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_count', models.PositiveSmallIntegerField(default=1)),
                ('break1_start', models.TimeField(blank=True, null=True)),
                ('break1_end', models.TimeField(blank=True, null=True)),
                ('break2_start', models.TimeField(blank=True, null=True)),
                ('break2_end', models.TimeField(blank=True, null=True)),
                ('total_break_minutes', models.PositiveIntegerField(default=60)),
                ('internship_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='break_config', to='places.internshipplace')),
            ],
            options={
                'db_table': 'break_configs',
            },
        ),
    ]
