# Generated by Django 6.0.2 on 2026-03-02 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='placements.studentplacement')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
